apiVersion: apps/v1
kind: Deployment
metadata:
  name: orphanage-deployment
  labels:
    app: orphanage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orphanage
  template:
    metadata:
      labels:
        app: orphanage
    spec:
      containers:
        - name: orphanage
          image: supungamage/orphanage:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: orphanage-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: orphanage-configmap
                  key: SPRING_ZIPKIN_BASEURL
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: orphanage-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: orphanage-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: orphanage-service
spec:
  selector:
    app: orphanage
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
