version: "3.8"

services:

  configserver:
    image: supungamage/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - supung

  eurekaserver:
    image: supungamage/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - supung
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  orphanage:
    image: supungamage/orphanage:latest
    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - supung
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  requirement:
    image: supungamage/requirement:latest
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      - supung
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  donation:
    image: supungamage/donation:latest
    mem_limit: 700m
    ports:
      - "8083:8083"
    networks:
      - supung
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

networks:
  supung:
